language: node_js
node_js:
  - "10.2"
sudo: enabled
install:
  - curl https://api.github.com/repos/GFY-oss/TIL/commits/54ff1a4f3e3513b4e4788a07bcfe27b8df6fb69e > dummy.json
  - node -e "console.log(require('./dummy.json'))"
  - export pusher=veera83372
  - npm install --global gatsby-cli
  - npm install
  - gatsby build
  - ls
  - pwd
  - env
  - cd ../ && git clone "https://$GITHUB_API@github.com/GFY-oss/til-sites.git"
  - ls
  - cd til-sites && mkdir "$pusher" && mv TIL/public/* ./
  - ls
  - ls -r ~
